#### 0. Numpy array was created with a for loop. Improve removing the loop.

```python
arr2d = np.zeros((10,10))
n_cols = arr2d.shape[1]
for i in range(n_cols):
    arr2d[i] = i
```

In [46]:
import numpy as np
np.arange(10).reshape(-1,1) * np.ones(10)
np.repeat(np.arange(10.).reshape(-1, 1), 10, axis=1)
np.tile(np.arange(10.).reshape(-1, 1), (1, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

#### 1. Import the numpy package under the name `np`

In [47]:
import numpy as np

#### 2. Create a null vector of size 10

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Find the memory size of an array 

In [49]:
array = np.array([0,1,2,3,4,5])
array.size * array.itemsize
array.__sizeof__()

136

#### 4. Create a vector of zeros of size 10 but the fifth value which is 1

In [50]:
zeros_10 = np.zeros(10)
zeros_10[4] = 1
zeros_10

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 5. Create a vector with values ranging from 10 to 49

In [51]:
vec = np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6. Reverse a vector (first element becomes last)

In [52]:
vec = np.arange(12)
vec = vec[::-1]
vec

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [53]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from [1,2,0,0,4,0]

In [54]:
arr = np.array([1,2,0,0,4,0])

arr.nonzero()

np.where(arr != 0)

(array([0, 1, 4], dtype=int64),)

#### 9. Create a 3x3 identity matrix

In [55]:
np.identity(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 10. Create a 3x3x3 array with random values

In [56]:
np.random.random((3,3,3))

array([[[0.67887953, 0.72063265, 0.58201979],
        [0.53737323, 0.75861562, 0.10590761],
        [0.47360042, 0.18633234, 0.73691818]],

       [[0.21655035, 0.13521817, 0.32414101],
        [0.14967487, 0.22232139, 0.38648898],
        [0.90259848, 0.44994999, 0.61306346]],

       [[0.90234858, 0.09928035, 0.96980907],
        [0.65314004, 0.17090959, 0.35815217],
        [0.75068614, 0.60783067, 0.32504723]]])

#### 11. Create a 10x10 array with random values and find the minimum and maximum values

In [57]:
np.random.seed(42)

arr = np.random.randint(1,100,(10,10))
print(arr)
print(arr.min(),arr.max())
print(np.min(arr),np.max(arr))

[[52 93 15 72 61 21 83 87 75 75]
 [88 24  3 22 53  2 88 30 38  2]
 [64 60 21 33 76 58 22 89 49 91]
 [59 42 92 60 80 15 62 62 47 62]
 [51 55 64  3 51  7 21 73 39 18]
 [ 4 89 60 14  9 90 53  2 84 92]
 [60 71 44  8 47 35 78 81 36 50]
 [ 4  2  6 54  4 54 93 63 18 90]
 [44 34 74 62 14 95 48 15 72 78]
 [87 62 40 85 80 82 53 24 26 89]]
2 95
2 95


#### 12. Create a random vector of size 30 and find the mean value

In [58]:
vec = np.random.random(30)
vec.mean()

0.4924721280668502

#### 13. Create a 2d array with 1 on the border and 0 inside

In [59]:
arr = np.zeros((5,6))
arr[0] = 1
arr[-1] = 1
arr[:,0] = 1
arr[:,-1] = 1
print(arr)

arr = np.zeros((5,6))
arr[:, [-1, 0]] = 1
arr[[-1, 0], :] = 1
print(arr)

arr = np.ones((5,6))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 14. How to add a border (filled with 0's) around an existing array?

In [60]:
arr = np.ones((5,6))
arr = np.pad(arr, pad_width=1, constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 15. What is the result of each of the following expressions?

- `0 * np.nan`
- `np.nan == np.nan`
- `np.inf > np.nan`
- `np.nan - np.nan`
- `np.nan in set([np.nan])`
- `0.3 == 3 * 0.1`

In [61]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan, np.inf <= np.nan)
print(np.nan - np.nan)
print(np.nan in {np.nan})
print(0.3 == 3 * 0.1)

nan
False
False False
nan
True
False


In [62]:
np.isclose(0.3, 3 * 0.1)

True

In [63]:
A = 3 * 0.1 * np.ones(5)
B = 0.3 * np.ones(5)
print(A,B)
print(A==B)
print(np.allclose(A,B))

[0.3 0.3 0.3 0.3 0.3] [0.3 0.3 0.3 0.3 0.3]
[False False False False False]
True


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [64]:
np.diag([1,2,3,4],k=-1)
np.diag(np.arange(4) + 1, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix of zeros and ones with a checkerboard pattern

In [65]:
arr = np.zeros((8,8),dtype=int)
arr[::2,1::2] = 1
arr[1::2,::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Create a checkerboard 8x8 matrix using the tile function

In [66]:
arr = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 19. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [67]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 20. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [68]:
np.random.seed(0)
arr = np.random.randint(0, 10, (5,3)) @ np.random.randint(0, 10, (3,2))
print(arr)

[[ 33  50]
 [ 76 122]
 [ 55  71]
 [ 79 114]
 [105 125]]


In [69]:
arr = np.random.default_rng(0).integers(0, 10, (5,3)) @ np.random.default_rng(0).integers(0, 10, (3,2))
print(arr)

[[109  60]
 [ 31  18]
 [  3   0]
 [121  60]
 [ 97  42]]


#### 21. Given a 1D array, negate all elements which are between 3 and 8, do it in place

In [70]:
arr = np.arange(12)
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [71]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 23. Create a random vector of size 10 and sort it 

In [72]:
arr = np.random.randint(0,10,10)
arr.sort()
print(arr)

[0 0 2 3 3 4 5 8 9 9]


#### 24. Consider two random arrays A and B, check if they are equal 

In [73]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

print(A == B)  # element-wise boolean mask
print(np.all(A == B)) # almost like allclose() but if shape mismatches, throws error

[1 0 1 1 1] [1 1 0 1 0]
False
False
[ True False False  True False]
False
