#### 1. Import the numpy package under the name `np`

In [9]:
import numpy as np

#### 2. Create a null vector of size 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Find the memory size of an array 

In [8]:
arr = np.arange(10)
arr.size * arr.itemsize

40

#### 4. Create a vector of zeros of size 10 but the fifth value which is 1

In [11]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 5. Create a vector with values ranging from 10 to 49

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6. Reverse a vector (first element becomes last)

In [13]:
arr = np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)
arr.nonzero()

(array([0, 1, 4], dtype=int64),)

#### 9. Create a 3x3 identity matrix

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 10. Create a 3x3x3 array with random values

In [24]:
np.random.randn(3,3,3)
np.random.default_rng(4).random((3,3,3))

array([[[0.94305611, 0.51132755, 0.97624371],
        [0.08083602, 0.60735583, 0.37648658],
        [0.80190121, 0.17452782, 0.87163527]],

       [[0.5439414 , 0.90221508, 0.47715352],
        [0.43049628, 0.78894672, 0.984153  ],
        [0.36972579, 0.96893287, 0.92902639]],

       [[0.17769259, 0.60885162, 0.70486475],
        [0.94280368, 0.66565742, 0.13339576],
        [0.4978676 , 0.49361983, 0.50022619]]])

#### 11. Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
arr = np.random.randint(0,10000,(10,10))
print(np.max(arr))

9689


#### 12. Create a random vector of size 30 and find the mean value

In [38]:
np.random.rand(30).mean()

0.4149127433264727

#### 13. Create a 2d array with 1 on the border and 0 inside

In [49]:
arr = np.zeros((6,7))
arr[[0,-1],:] = 1
arr[:, [0,-1]]=1

arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 14. How to add a border (filled with 0's) around an existing array?

In [1]:
arr = np.ones((3,5))
np.pad(arr, pad_width=2, constant_values=0)

NameError: name 'np' is not defined

#### 15. What is the result of each of the following expressions?

- `0 * np.nan`
- `np.nan == np.nan`
- `np.inf > np.nan`
- `np.nan - np.nan`
- `np.nan in set([np.nan])`
- `0.3 == 3 * 0.1`

In [62]:
np.nan - np.nan

nan

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 17. Create a 8x8 matrix of zeros and ones with a checkerboard pattern

#### 18. Create a checkerboard 8x8 matrix using the tile function

#### 19. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

#### 20. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

#### 21. Given a 1D array, negate all elements which are between 3 and 8, do it in place

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

#### 23. Create a random vector of size 10 and sort it 

#### 24. Consider two random arrays A and B, check if they are equal 