In [8]:
import numpy as np
import pandas as pd

A= np.arange(1,21)
A = A.reshape(5,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [9]:
row_sums = np.sum(A, axis=1)   # sum of rows in a list
column_sums = np.sum(A, axis=0) # sum of colunns in a list

print(row_sums, column_sums)

np.sum(row_sums), np.sum(column_sums)  # sum of rows (total), sum of columns(total)

[10 26 42 58 74] [45 50 55 60]


(np.int64(210), np.int64(210))

In [6]:
def row_vector(list):  #take a list as a function and return in a row vector
    return np.array(list).reshape(1,len(list))

s = row_vector([1,2,3])
print(s)

[[1 2 3]]


In [7]:
def column_vector(list):  #take a list as a function and return in a column vector
    return np.array(list).reshape(len(list),1)