In [1]:
import numpy as np
x = np.array([1+2j,3-4j])
display(x.real)
display(x.imag)

array([1., 3.])

array([ 2., -4.])

In [35]:
import numpy as np

# Simulate 10 coin tosses (1 = heads, 0 = tails)
tosses = np.random.randint(0, 2, 10) # 10 numbers between 0 and 1 (2 is not included)

print("Coin toss results:", tosses)
print("Number of heads:", np.sum(tosses))
print("Proportion of heads:", np.mean(tosses))


Coin toss results: [0 0 1 1 1 1 1 0 1 1]
Number of heads: 7
Proportion of heads: 0.7


In [22]:
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [28]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((2,3))  # if you dont specify dtype it will take float as default

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.eye(3, 4, k=0) # 3 rows, 4 columns, diagonal at k=0 (main diagonal), if i do k=1 it will shift the diagonal one step up

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.identity(2)  # for identity matrix

array([[1., 0.],
       [0., 1.]])

In [45]:
x= np.random.random((2,3))
print(x)
y = np.random.randn(1,2)
print(y)

[[0.0884925  0.19598286 0.04522729]
 [0.32533033 0.38867729 0.27134903]]
[[-0.46063877  1.05712223]]


In [ ]:
np.randomseed(42)  # if i want to use the same random numbers again and again

In [46]:
np.random.randint(1, 100, (2,2))

array([[60, 41],
       [29, 15]])

In [8]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
sang = arr.shape
print(sang)
x= np.average(arr)
print(x)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
4.5


In [15]:
arr = np.arange(1,10)
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr = np.zeros(8,dtype="int")
arr[1::2] = 1
print(arr)
arr.reshape(2,4)

[0 1 0 1 0 1 0 1]


array([[0, 1, 0, 1],
       [0, 1, 0, 1]])

In [38]:
arr = np.arange(10).reshape(2,5)
np.savetxt("myfile.csv", arr, delimiter=",")



In [1]:
import pandas as pd

In [9]:
dataset = {
    "Students":["Alice", "Bob", "Charlie", "David"],
    "Scores":[85, 92, 78, 90],
    "Passed":[True, True, False, True]
}
df = pd.DataFrame(dataset)
df

Students  Scores  Passed
0    Alice      85    True
1      Bob      92    True
2  Charlie      78   False
3    David      90    True